/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fast_framework_ndk_SampleHelper */

#ifndef _Included_com_fast_framework_ndk_SampleHelper
#define _Included_com_fast_framework_ndk_SampleHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fast_framework_ndk_SampleHelper
 * Method:    getHelloJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fast_framework_ndk_SampleHelper_getHelloJni
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
