/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fast_framework_ndk_AESHelper */

#ifndef _Included_com_fast_framework_ndk_AESHelper
#define _Included_com_fast_framework_ndk_AESHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fast_framework_ndk_AESHelper
 * Method:    getAESKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fast_framework_ndk_AESHelper_getAESKey
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
